package com.hyt.mapper;

import com.github.pagehelper.Page;
import com.hyt.model.Tables;
import com.hyt.model.TablesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TablesMapper {

    /**
     * 返回所有的表单数据
     * @return
     */
    public List<Tables> findAllTables();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int countByExample(TablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int deleteByExample(TablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int insert(Tables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int insertSelective(Tables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    List<Tables> selectByExample(TablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    Tables selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tables record, @Param("example") TablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int updateByExample(@Param("record") Tables record, @Param("example") TablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int updateByPrimaryKeySelective(Tables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables
     *
     * @mbggenerated Thu Aug 01 10:09:54 CST 2019
     */
    int updateByPrimaryKey(Tables record);

    /**
     * 插件 分页  查询表中所有字段
     */
    Page<Tables> findWithBLOBsByPage();
}